apiVersion: v1
kind: Service
metadata:
  labels:
    app: nuget
  name: nuget
spec:
  metadata:
    annotations:
      timestamp: "{{ now | unixEpoch }}"
  selector:
    app: nuget
  type: ClusterIP    
  ports:
  - name: nuget
    port: 80
    protocol: TCP
    targetPort: 80
  
